# Generated by Django 5.2.7 on 2025-10-21 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(blank=True, max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.CharField(max_length=255)),
                ('gioi_tinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('ngay_tham_gia', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuc_vu', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.CharField(max_length=255)),
                ('ngay_vao_lam', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuanTriVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quyen_han', models.CharField(default='Toàn quyền', max_length=100)),
                ('ngay_tao_quyen', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThuCung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thucung', models.CharField(max_length=100)),
                ('loai', models.CharField(max_length=100)),
                ('tuoi', models.IntegerField()),
                ('ghi_chu', models.TextField(blank=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
            ],
        ),
    ]
