# Generated by Django 5.2.7 on 2025-11-24 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=100),
        ),

        migrations.CreateModel(
            name='LichSuTichDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_diem', models.IntegerField()),
                ('noi_dung', models.CharField(max_length=255)),
                ('ngay_cap_nhat', models.DateTimeField(default=django.utils.timezone.now)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='TichDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_diem', models.IntegerField(default=0)),
                ('cap_bac', models.CharField(default='Thành viên mới', max_length=50)),
                ('khach_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tich_diem', to='TK.khachhang')),
            ],
        ),

    ]
