# Generated by Django 5.2.7 on 2025-11-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0002_remove_nhanvien_chuc_vu_nhanvien_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='chuc_vu',
        ),
    ]
