# Generated by Django 5.2.8 on 2025-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TK', '0003_remove_nhanvien_chuc_vu_thucung_can_nang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thucung',
            name='can_nang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='QuanTriVien',
        ),
    ]
