# Generated by Django 5.2.8 on 2025-11-26 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TK', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id_tinnhan', models.AutoField(primary_key=True, serialize=False)),
                ('nguoi_gui', models.CharField(choices=[('KH', 'Khách hàng'), ('NV', 'Nhân viên'), ('AD', 'Quản trị viên'), ('HT', 'Hệ thống')], max_length=5)),
                ('noi_dung', models.TextField()),
                ('thoi_gian_gui', models.DateTimeField(default=django.utils.timezone.now)),
                ('phien_chat', models.CharField(blank=True, max_length=50, null=True)),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_khachhang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
                ('id_nhanvien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TK.nhanvien')),
            ],
        ),
    ]
