# Generated by Django 5.2.8 on 2025-11-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinnhan',
            name='da_doc',
            field=models.BooleanField(default=False),
        ),
    ]
