"""
Django settings for CSKH project.


Generated by 'django-admin startproject' using Django 4.2.8.


For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/


For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k-(94ab4v*^9to(qa1v%ass=ao+0@csq__b^08t&gv^fkt$0jr'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []




# Application definition


INSTALLED_APPS = [
   'jazzmin',
   'django.contrib.admin',
   'django.contrib.auth',
   'django.contrib.contenttypes',
   'django.contrib.sessions',
   'django.contrib.messages',
   'django.contrib.staticfiles',
   'django.contrib.humanize',
   'TK',
   'trangchu',
   'TB',
   'LichHen',
   'DV',
    'Chat',
   'KhieunaiDanhgia',
]


MIDDLEWARE = [
   'django.middleware.security.SecurityMiddleware',
   'django.contrib.sessions.middleware.SessionMiddleware',
   'django.middleware.common.CommonMiddleware',
   'django.middleware.csrf.CsrfViewMiddleware',
   'django.contrib.auth.middleware.AuthenticationMiddleware',
   'django.contrib.messages.middleware.MessageMiddleware',
   'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'CSKH.urls'


TEMPLATES = [
   {
       'BACKEND': 'django.template.backends.django.DjangoTemplates',
       'DIRS': [BASE_DIR / 'templates'],
       'APP_DIRS': True,
       'OPTIONS': {
           'context_processors': [
               'django.template.context_processors.debug',
               'django.template.context_processors.request',
               'django.contrib.auth.context_processors.auth',
               'django.contrib.messages.context_processors.messages',
               'TB.context_processors.thong_bao_moi',




           ],
       },
   },
]


WSGI_APPLICATION = 'CSKH.wsgi.application'




# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': BASE_DIR / 'db.sqlite3',
   }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
   # {
   #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
   # },
   {
       'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
   },
   # {
   #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
   # },
   # {
   #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
   # },
]




# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Ho_Chi_Minh'


USE_I18N = True


USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'


import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATICFILES_DIRS = [
   BASE_DIR / "static",
]




LOGIN_URL = '/dangnhap/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'






JAZZMIN_SETTINGS = {
   "site_title": "Punky Spa",
   "site_header": "Punky Spa",
   "site_brand": "🐾 Punky Spa",
   "welcome_sign": "Welcome to Punky Spa Admin Dashboard",
   "site_logo": "trangchu/logo.png",
   "copyright": "© 2025 Punky Spa Team",
   "show_ui_builder": False,
   "custom_css": "admin_custom.css",
   "usermenu_links": [
       {"name": "Trang chủ", "url": "/", "new_window": False},
   ],
}






# 🎀 Tùy chỉnh theme toàn trang
JAZZMIN_UI_TWEAKS = {
   "theme": "flatly",  # nền sáng
   "dark_mode_theme": None,
   "navbar": "navbar-pink",  # thanh trên
   "sidebar": "sidebar-light-pink",  # sidebar
   "brand_colour": "navbar-pink",
   "accent": "pink",
   "navbar_fixed": True,
   "sidebar_fixed": True,
   "footer_fixed": False,
   "sidebar_nav_compact_style": True,
   "button_classes": {
       "primary": "btn-pink",
       "success": "btn-pink",
       "info": "btn-pink",
   },
}
