# Generated by Django 5.2.7 on 2025-11-25 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LichHen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Mức độ hài lòng')),
                ('nhan_xet', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True)),
                ('lich_hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_list', to='LichHen.lichhen')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KhieuNai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(verbose_name='Nội dung khiếu nại')),
                ('minh_chung', models.FileField(blank=True, null=True, upload_to='minhchung/', verbose_name='Minh chứng (ảnh hoặc video)')),
                ('yeu_cau', models.TextField(blank=True, verbose_name='Yêu cầu/mong muốn')),
                ('phan_hoi', models.TextField(blank=True, null=True, verbose_name='Phản hồi / Ghi chú từ nhân viên')),
                ('trang_thai', models.CharField(choices=[('Chờ xử lý', 'Chờ xử lý'), ('Đang xử lý', 'Đang xử lý'), ('Đã phản hồi', 'Đã phản hồi')], default='Chờ xử lý', max_length=30)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('lich_hen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khieu_nai_list', to='LichHen.lichhen')),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nhan_vien_phu_trach', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khieunai_phu_trach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
