# Generated by Django 5.2.7 on 2025-11-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhieunaiDanhgia', '0001_initial'),
        ('LichHen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='lich_hen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='LichHen.lichhen'),
        ),
        migrations.AlterField(
            model_name='khieunai',
            name='lich_hen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khieu_nai', to='LichHen.lichhen'),
        ),
    ]
