# Generated by Django 5.2.7 on 2025-11-28 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhieunaiDanhgia', '0002_alter_danhgia_lich_hen_alter_khieunai_lich_hen'),
        ('LichHen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khieunai',
            name='lich_hen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='khieu_nai', to='LichHen.lichhen'),
        ),
    ]
