# Generated by Django 5.2.7 on 2025-11-29 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhieunaiDanhgia', '0003_alter_khieunai_lich_hen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='khieunai',
            name='minh_chung',
            field=models.FileField(upload_to='minhchung/', verbose_name='Minh chứng (ảnh hoặc video)'),
        ),
        migrations.AlterField(
            model_name='khieunai',
            name='nhan_vien_phu_trach',
            field=models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='khieunai_phu_trach', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khieunai',
            name='phan_hoi',
            field=models.TextField(verbose_name='Phản hồi / Ghi chú từ nhân viên', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='khieunai',
            name='yeu_cau',
            field=models.TextField(verbose_name='Yêu cầu/mong muốn'),
        ),
    ]
