# Generated by Django 5.2.7 on 2025-11-29 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhieunaiDanhgia', '0004_alter_khieunai_minh_chung_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='khieunai',
            name='minh_chung',
            field=models.FileField(blank=True, null=True, upload_to='minhchung/', verbose_name='Minh chứng (ảnh hoặc video)'),
        ),
        migrations.AlterField(
            model_name='khieunai',
            name='nhan_vien_phu_trach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='khieunai_phu_trach', to=settings.AUTH_USER_MODEL),
        ),
    ]
