# Generated by Django 5.2.7 on 2025-11-25 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DV', '0001_initial'),
        ('TK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_dien_thoai', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải gồm đúng 10 chữ số.', regex='^\\d{10}$')], verbose_name='Số điện thoại')),
                ('thoi_gian', models.DateTimeField(help_text='Thời gian thực hiện dịch vụ.')),
                ('ghi_chu', models.TextField(blank=True, help_text='Ghi chú đặc biệt của khách hàng.')),
                ('trang_thai', models.CharField(choices=[('sap_toi', 'Sắp tới'), ('hoan_thanh', 'Hoàn thành'), ('huy', 'Đã hủy')], default='sap_toi', max_length=20)),
                ('ly_do_huy', models.TextField(blank=True, null=True)),
                ('da_nhac', models.BooleanField(default=False, help_text='Đánh dấu nếu đã gửi thông báo nhắc lịch cho khách.')),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('khach_hang', models.ForeignKey(help_text='Khách hàng đặt lịch hẹn.', on_delete=django.db.models.deletion.CASCADE, to='TK.khachhang')),
                ('nhan_vien', models.ForeignKey(blank=True, help_text='Nhân viên phụ trách dịch vụ.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TK.nhanvien')),
                ('thu_cung', models.ForeignKey(help_text='Thú cưng được chăm sóc.', on_delete=django.db.models.deletion.CASCADE, to='TK.thucung')),
            ],
        ),
        migrations.CreateModel(
            name='DV_LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DV.dichvu')),
                ('lich_hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichHen.lichhen')),
            ],
        ),
    ]
