# Generated by Django 5.2.5 on 2025-11-11 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=100)),
                ('noi_dung', models.TextField()),
                ('loai', models.CharField(choices=[('lich_hen', 'Lịch hẹn'), ('khieu_nai', 'Khiếu nại'), ('he_thong', 'Hệ thống')], default='lich_hen', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('da_doc', models.BooleanField(default=False)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('dich_vu', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, help_text='Đường dẫn khi người dùng bấm vào thông báo', max_length=300, null=True)),
                ('doi_tuong_id', models.PositiveIntegerField(blank=True, null=True)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thongbao_gui', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thongbao_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
