# Generated by Django 5.2.7 on 2025-12-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='khuyenmai/'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='loai',
            field=models.CharField(choices=[('lich_hen', 'Lịch hẹn'), ('khuyen_mai', 'Khuyến mãi'), ('khieu_nai', 'Khiếu nại')], default='lich_hen', max_length=20),
        ),
    ]
