# Generated by Django 5.2.7 on 2025-11-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dich_vu', models.CharField(max_length=100, verbose_name='Tên dịch vụ')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('gia', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='dichvu/', verbose_name='Hình ảnh')),
            ],
        ),
    ]
