# Generated by Django 5.2.8 on 2025-12-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichvu',
            name='gia',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá'),
        ),
    ]
